# ***************************************
# * Parameters for metassemble pipeline *
# ***************************************

#list_files: "/work/sycuro_lab/kevin/tkg_pilot_project_2021/scripts/metawrap_job_arrays/KG_files.txt"

list_files: "/work/sycuro_lab/kevin/tkg_pilot_project_2021/scripts/metawrap_job_arrays/KG_1_file.txt"

# Path to sequences
input_dir: "/work/sycuro_lab/kevin/tkg_pilot_project_2021/metqc_tkg_2021-06-23/bmtagger"

output_dir: "/work/sycuro_lab/kevin/metawrap_analysis_test_2021-12-28"

# Suffix for forward reads.
forward_read_suffix: "_bmtagged_1.fastq"

# Suffix for reverse reads.
reverse_read_suffix: "_bmtagged_2.fastq"


## metawrap assembly parameters

# Number of threads for the metawrap assembly module.
assembler_threads: 14

# Minumum contig length.
min_contig_length: 500

# Memory in GB.
memory_in_gb: 180

## metagenome quast parameters.

# Number of threads for quast metagenome assembly rule.
quast_threads: 14

## metagenome prokka parameters.

# Number of threads for prokka  metagenome assembly rule.
prokka_threads: 14

## metawrap binning parameters.

# Number of threads for the metawrap binning module.
binning_threads: 14

## metawrap bin_refinement parameters.
#
# Number of threads for the metawrap bin_refinement module.
bin_refinement_threads: 14

# Completeness threshold to filter MAGs (completeness >= completeness_thresh)
completeness_thresh: 50

# Contamination threshold to filter MAGs. (contamination >= contamination_thresh)
contamination_thresh: 10




