# ***************************************
# * Parameters for metassemble pipeline *
# ***************************************

list_files: "/home/kevin.muirhead/metqc_update/metqc/KG_files.txt"

#list_files: "/home/kevin.muirhead/metqc_update/metqc/KG_1_file.txt"

# Path to sequences
input_dir: "/work/sycuro_lab/kevin/metqc_test_2021-06-23/bmtagger"

output_dir: "/work/sycuro_lab/kevin/metawrap_analysis_2021-07-10"

# The number of threads for metaWRAP modules.
threads: 14

# Suffix for forward reads.
forward_read_suffix: "_bmtagged_1.fastq"

# Suffix for reverse reads.
reverse_read_suffix: "_bmtagged_2.fastq"


