# ***************************************
# * Parameters for metagenotate pipeline *
# ***************************************

#list_files: "/home/kevin.muirhead/metagenotate/sample_list.txt"

list_files: "/home/kevin.muirhead/metagenotate/sample_list.txt"

# Path to sequences
input_dir: "/work/sycuro_lab/kevin/project/clean_reads/bmtagger/"

output_dir: "/work/sycuro_lab/kevin/metagenotate_all_samples_2022-05-17"

# Suffix for forward reads.
forward_read_suffix: "_bmtagged_1.fastq"

# Suffix for reverse reads.
reverse_read_suffix: "_bmtagged_2.fastq"


## metawrap assembly parameters

metawrap_path: "/bulk/IMCshared_bulk/shared/shared_software/metaWRAP/bin"

# Number of threads for the metawrap assembly module.
assembler_threads: 14

# Minumum contig length.
min_contig_length: 500

# Memory in GB.
memory_in_gb: 180

## metagenome quast parameters.

# Number of threads for quast metagenome assembly rule.
quast_threads: 14

##  prokka parameters.

# Number of threads for prokka  metagenome assembly rule.
prokka_threads: 14

## metaerg parameters.

# metaerg database path.
metaerg_database_path: "/bulk/IMCshared_bulk/shared/dbs/metaerg_db/db"

# singularity working directories.
working_dirs: ["/work","/bulk"]

metaerg_threads: 14


## metawrap binning parameters.

# Number of threads for the metawrap binning module.
binning_threads: 14

## metawrap bin_refinement parameters.
#
# Number of threads for the metawrap bin_refinement module.
bin_refinement_threads: 14

# Completeness threshold to filter MAGs (completeness >= completeness_thresh)
completeness_thresh: 50

# Contamination threshold to filter MAGs. (contamination >= contamination_thresh)
contamination_thresh: 10

## CheckM parameters.

checkm_database_path: "/bulk/IMCshared_bulk/shared/dbs/checkm_db"

checkm_threads: 14

## GTDB-tk parameters.

gtdbtk_database_path: "/bulk/IMCshared_bulk/shared/dbs/gtdbtk-1.5.0/db"

gtdbtk_threads: 14

