# ***************************************
# * Parameters for metagenotate pipeline *
# ***************************************

#list_files: "/home/kevin.muirhead/metagenotate/sample_list.txt"

#list_files: "/work/sycuro_lab/kevin/reworking_metagenotate/PD_306_Novaseq_metagenotate/metagenotate/PD_306_samples_list.txt"
list_files: "/work/sycuro_lab/kevin/reworking_metagenotate/PD_306_Novaseq_metagenotate/metagenotate/PD_no_blnk_Zymo_samples_list.txt"

#list_files: "/work/sycuro_lab/kevin/reworking_metagenotate/PD_306_Novaseq_metagenotate/metagenotate/sample_list.txt"

# Path to sequences
input_dir: "/bulk/IMCshared_bulk/sycuro_shared_projects/PD_306_Novaseq/bmtagger"

output_dir: "/bulk/IMCshared_bulk/sycuro_shared_projects/PD_306_Novaseq/metagenotate"

# Suffix for forward reads.
forward_read_suffix: "_bmtagged_1.fastq"

# Suffix for reverse reads.
reverse_read_suffix: "_bmtagged_2.fastq"


## metawrap assembly parameters

metawrap_path: "/bulk/IMCshared_bulk/shared/shared_software/metaWRAP/bin"

# Number of threads for the metawrap assembly module.
assembler_threads: 28

# Memory in GB.
memory_in_gb: 220

## Filter by length

# Minimum sequence length of the final metagenome assembly file. Default: 500
min_sequence_length: 500

# Minumum contig length for binning programs.
min_contig_length: 1500

## metagenome quast parameters.

# Number of threads for quast metagenome assembly rule.
quast_threads: 14

##  prokka parameters.

# Number of threads for prokka  metagenome assembly rule.
prokka_threads: 14

## metaerg parameters.

# metaerg database path.
metaerg_database_path: "/bulk/IMCshared_bulk/shared/dbs/metaerg_db/db"

# singularity working directories.
working_dirs: ["/work","/bulk"]

metaerg_threads: 14


## metawrap binning parameters.
maxbin2_path: "/bulk/IMCshared_bulk/shared/shared_software/maxbin2"
maxbin2_markers: 107

# Number of threads for the metawrap binning module.
binning_threads: 14

## metawrap bin_refinement parameters.
#
# Number of threads for the metawrap bin_refinement module.
bin_refinement_threads: 14

# Completeness threshold to filter MAGs (completeness >= completeness_thresh)
completeness_thresh: 50

# Contamination threshold to filter MAGs. (contamination >= contamination_thresh)
contamination_thresh: 10

## CheckM parameters.

checkm_database_path: "/bulk/IMCshared_bulk/shared/dbs/checkm_db"

checkm_threads: 28

## GTDB-tk parameters.

gtdbtk_database_path: "/bulk/IMCshared_bulk/shared/dbs/gtdbtk-1.5.0/db"

gtdbtk_threads: 28


